apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksm
  template:
    metadata:
      labels:
        app: ksm
    spec:
      containers:
      - image: okteto.dev/ksm:latest
        name: ksm
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "1d3d8f66-9338-46c5-aa46-cf930116323d"
        - name: Vless_Path
          value: "/gxfr4er"
        - name: Vmess_UUID
          value: "1d3d8f66-9338-46c5-aa46-cf930116323d"
        - name: Vmess_Path
          value: "/bxgf58nhg"
        - name: Share_Path
          value: "/v2link"
